INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_RADIOTELETYPE gnuradio-radioteletype)

FIND_PATH(
    GNURADIO_RADIOTELETYPE_INCLUDE_DIRS
    NAMES radioteletype/async_word_extractor_bb.h
    HINTS $ENV{GNURADIO_RADIOTELETYPE_DIR}/include
        ${PC_GNURADIO_RADIOTELETYPE_INCLUDEDIR}
        ${CMAKE_INSTALL_PREFIX}/include/radioteletype
    PATHS /usr/local/include/radioteletype
          /usr/include/radioteletype
)

FIND_LIBRARY(
    GNURADIO_RADIOTELETYPE_LIBRARIES
    NAMES gnuradio-radioteletype
    HINTS $ENV{GNURADIO_RADIOTELETYPE_DIR}/lib
        ${PC_GNURADIO_RADIOTELETYPE_LIBDIR}
        ${CMAKE_INSTALL_PREFIX}/lib
        ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_RADIOTELETYPE DEFAULT_MSG GNURADIO_RADIOTELETYPE_LIBRARIES GNURADIO_RADIOTELETYPE_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_RADIOTELETYPE_LIBRARIES GNURADIO_RADIOTELETYPE_INCLUDE_DIRS)
